services:
  - type: web
    name: ml-services
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port=8080 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0